name             'tectonic-chef'
maintainer       'James Hebden'
maintainer_email 'james@tectonic.com.au'
license          'MIT'
description      'Configures chef server for operation on EC2'
long_description 'Configures chef server for operation on EC2 via Vagrant. Used as part of the chef-server repo to tie community cookbooks together.'
version          '0.1.0'
depends		 'heka'
depends		 'chef-server'
depends		 'swap'
